-- use this file to map the AP item ids to your items
-- first value is the code of the target item and the second is the item type override. The third value is an optional increment multiplier for consumables. (feel free to expand the table with any other values you might need (i.e. special initial values, etc.)!)
-- here are the SM items as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/item_mapping.lua
SETTING_MAPPING = {
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
 ["Include_Temple"] = "YesTemple",
},

ITEM_MAPPING = {
 [1] = {{"PV1500Nozzles"}},
 [2] = {{"PV3000Nozzles"}},
 [3] = {{"UrbanXU2Nozzles"}},
 [4] = {{"PVProNozzles"}},
 [5] = {{"PV1500Extensions"}},
 [6] = {{"PV3000Extensions"}},
 [7] = {{"UrbanXU2Extensions"}},
 [8] = {{"PVProExtensions"}},
 [9] = {{"StepStool"}},
 [10] = {{"Ladder"}},
 [11] = {{"Scaffolding"}},
}
